### ISSUE TITLE
Context to Run Examples

### ISSUE THREAD

**Issue by elissonmichael** [kirshin/hyperledger-fabric-sdk#5]
Hi @kirshin, I have a lot of interest for this SDK. 

I'm trying to run the examples, but unsuccessfully. 
I tried executing enroll_user.rb (with or without ssl) using Ruby 2.6.5 and 2.6.0.
I have my environment already configured to run [this hyperledger project and it is working](https://github.com/IBM/raft-fabric-sample). 
I was hoping to have some more instructions on what I'm missing to start using Ruby with HyperLedger.

Thank you for you attention.

**Comment by kirshin** [comment]
Hi Élisson Michael

Thank you for your interest in this project

In the attachment files for working with your example.
In the init.rb you need to specify the path to the crypto materials

**Comment by elissonmichael** [comment]
@kirshin thank you for your feedback.
I've managed to make it work with a rails, but I'm only able to do a `query` method. 

Everytime I try to use `invoke` I got an `GRPC::Unavailable (14:DNS resolution failed)`.
Do you have any tips to where should I check first?

[This is the repository where I'll document this working sample](https://github.com/elissonmichael/rails-hyperledger-blockchain-scaffold).

**Comment by elissonmichael** [comment]
@kirshin thank you for your feedback.
I've managed to make it work with a rails application.
This is the repository where I'll document this working sample.
